title: Page

fields:
  title:
    label: Title
    type:  text

  headline:
    label: Headline
    type: text

  text:
    label: Text
    type:  textarea

  logos:
    label: logos
    type: textarea


